spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/project?currentSchema=project

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1